apiVersion: apps/v1
kind: Deployment
metadata:
  name: chainlink-deployment
  labels:
    app: chainlink-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chainlink-node
  template:
    metadata:
      labels:
        app: chainlink-node
    spec:
      containers:
        - name: chainlink
          image: smartcontract/chainlink:latest
          #command: ["/bin/bash", "-c", "echo $(ETH_URL)"]
          args: ["local", "n", "-p",  "/chainlink/.password", "-a", "/chainlink/.api"]
          envFrom:
          - configMapRef:
              name: node-env
          ports:
          - containerPort: 6689
          volumeMounts:
            - name: api-volume
              mountPath: /chainlink/.api
              subPath: .api
            - name: password-volume
              mountPath: /chainlink/.password
              subPath: .password
          livenessProbe:
            httpGet:
              path: /
              port: 6689
              httpHeaders:
              - name: Content-Type
                value: text-html; charset=utf-8
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: api-volume
          configMap:
            name: api-env
        - name: password-volume
          configMap:
            name: password-env